name: Flutter Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v1.5.1
        with:
          flutter-version: '2.2.1'
      
      - name: Retrieve packages
        run: flutter pub get
        
      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage

      - name: Upload coverage to codecov
        run: curl -s https://codecov.io/bash -t ${{ secrets.CODECOV_TOKEN }}
        shell: bash
